import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import io, { Socket } from "socket.io-client";
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [socket, setSocket] = useState<Socket>()
  const [messages, setMessages] = useState<string[]>()
  const handleSubmit = (value: string) => {
    socket?.emit("message", value)
  }
  useEffect(()=>{
    const socket = io("http://localhost:8001");
    setSocket(socket)
  },[setSocket])
  const messageListener = (message: string)=>{
    setMessages([])
  }
  return (
    <>
      <Head>
        <title>Chat Board</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>

        </main>
    </>
  )
}
